language: node_js
node_js:
 - 8.10.0
branches:
  only:
    - dev
    - edge
install:
  - npm install
script:
  - npm test
  - eslint "src/**"
  - jsdoc src -r
repo: https://github.com/CarPalFleet/Javascript-SDK
